import type { UserRole } from '@/contexts/AuthContext';

export const PERMISSIONS = {
  // Tab-level
  FUNC_TAB_HOME: 'FUNC_TAB_HOME',
  FUNC_TAB_FEED: 'FUNC_TAB_FEED',
  FUNC_TAB_SKATE_SQUARE: 'FUNC_TAB_SKATE_SQUARE',
  FUNC_TAB_PODCAST: 'FUNC_TAB_PODCAST',
  FUNC_TAB_SETTINGS: 'FUNC_TAB_SETTINGS',
  // Feature-level: settings/admin
  FUNC_TAB_SETTINGS_MANAGE_USERS: 'FUNC_TAB_SETTINGS_MANAGE_USERS',
  FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT: 'FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT',
  FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE: 'FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE',
  FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE: 'FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE',
  FUNC_TAB_SETTINGS_CONFIGURE_AUTH: 'FUNC_TAB_SETTINGS_CONFIGURE_AUTH',
  FUNC_TAB_SETTINGS_SESSION_CONFIG: 'FUNC_TAB_SETTINGS_SESSION_CONFIG',
  FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS: 'FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS',
  FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS: 'FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS',
  FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT: 'FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const STANDARD_PERMISSIONS: Permission[] = [
  PERMISSIONS.FUNC_TAB_HOME,
  PERMISSIONS.FUNC_TAB_FEED,
  PERMISSIONS.FUNC_TAB_SKATE_SQUARE,
  PERMISSIONS.FUNC_TAB_PODCAST,
  PERMISSIONS.FUNC_TAB_SETTINGS,
];

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  standard: STANDARD_PERMISSIONS,
  admin: [
    ...STANDARD_PERMISSIONS,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE,
    PERMISSIONS.FUNC_TAB_SETTINGS_CONFIGURE_AUTH,
    PERMISSIONS.FUNC_TAB_SETTINGS_SESSION_CONFIG,
    PERMISSIONS.FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS,
    PERMISSIONS.FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS,
    PERMISSIONS.FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT,
  ],
};
