import type {UserRole} from '@core/contexts/AuthContext';

export const PERMISSIONS = {
  // Tab-level
  FUNC_TAB_HOME: 'FUNC_TAB_HOME',
  FUNC_TAB_FEED: 'FUNC_TAB_FEED',
  FUNC_TAB_SKATE_SQUARE: 'FUNC_TAB_SKATE_SQUARE',
  FUNC_TAB_PODCAST: 'FUNC_TAB_PODCAST',
  FUNC_TAB_SETTINGS: 'FUNC_TAB_SETTINGS',
  // Feature-level: settings/admin
  FUNC_TAB_SETTINGS_MANAGE_USERS: 'FUNC_TAB_SETTINGS_MANAGE_USERS',
  FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT: 'FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT',
  FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE: 'FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE',
  FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE: 'FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE',
  FUNC_TAB_SETTINGS_CONFIGURE_AUTH: 'FUNC_TAB_SETTINGS_CONFIGURE_AUTH',
  FUNC_TAB_SETTINGS_SESSION_CONFIG: 'FUNC_TAB_SETTINGS_SESSION_CONFIG',
  FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS: 'FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS',
  FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS: 'FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS',
  FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT: 'FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const STANDARD_PERMISSIONS: Permission[] = [
  PERMISSIONS.FUNC_TAB_SETTINGS,
];

export const PERMISSION_LABELS: Record<Permission, string> = {
  FUNC_TAB_HOME: 'Home Tab',
  FUNC_TAB_FEED: 'Feed Tab',
  FUNC_TAB_SKATE_SQUARE: 'Skate Square Tab',
  FUNC_TAB_PODCAST: 'Podcast Tab',
  FUNC_TAB_SETTINGS: 'Settings Tab',
  FUNC_TAB_SETTINGS_MANAGE_USERS: 'Manage Users',
  FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT: 'Create Users',
  FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE: 'Edit Users',
  FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE: 'Delete Users',
  FUNC_TAB_SETTINGS_CONFIGURE_AUTH: 'Configure Authentication',
  FUNC_TAB_SETTINGS_SESSION_CONFIG: 'Session Configuration',
  FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS: 'Language Settings',
  FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS: 'Profile Restrictions',
  FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT: 'Navigation Management',
};

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  guest: [
    PERMISSIONS.FUNC_TAB_HOME,
    PERMISSIONS.FUNC_TAB_SETTINGS,
  ],
  standard: STANDARD_PERMISSIONS,
  admin: [
    ...STANDARD_PERMISSIONS,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE,
    PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE,
    PERMISSIONS.FUNC_TAB_SETTINGS_CONFIGURE_AUTH,
    PERMISSIONS.FUNC_TAB_SETTINGS_SESSION_CONFIG,
    PERMISSIONS.FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS,
    PERMISSIONS.FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS,
    PERMISSIONS.FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT,
  ],
};
