export const PERMISSIONS = {
  // Tab-level
  FUNC_TAB_HOME: 'FUNC_TAB_HOME',
  FUNC_TAB_FEED: 'FUNC_TAB_FEED',
  FUNC_TAB_SKATE_SQUARE: 'FUNC_TAB_SKATE_SQUARE',
  FUNC_TAB_PODCAST: 'FUNC_TAB_PODCAST',
  FUNC_TAB_SETTINGS: 'FUNC_TAB_SETTINGS',
  // Feature-level: settings/admin
  FUNC_TAB_SETTINGS_MANAGE_USERS: 'FUNC_TAB_SETTINGS_MANAGE_USERS',
  FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT: 'FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT',
  FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE: 'FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE',
  FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE: 'FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE',
  FUNC_TAB_SETTINGS_CONFIGURE_AUTH: 'FUNC_TAB_SETTINGS_CONFIGURE_AUTH',
  FUNC_TAB_SETTINGS_SESSION_CONFIG: 'FUNC_TAB_SETTINGS_SESSION_CONFIG',
  FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS: 'FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS',
  FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS: 'FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS',
  FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT: 'FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT',
  FUNC_TAB_SETTINGS_BRANDING: 'FUNC_TAB_SETTINGS_BRANDING',
  // Feature-level: feed/posts
  FUNC_FEED_CREATE_POST: 'FUNC_FEED_CREATE_POST',
  FUNC_FEED_EDIT_POST: 'FUNC_FEED_EDIT_POST',
  FUNC_FEED_DELETE_POST: 'FUNC_FEED_DELETE_POST',
  FUNC_FEED_CONFIGURE: 'FUNC_FEED_CONFIGURE',
  FUNC_FEED_IMPORT_JSON: 'FUNC_FEED_IMPORT_JSON',
  // Feature-level: podcast
  FUNC_PODCAST_CREATE_POST: 'FUNC_PODCAST_CREATE_POST',
  FUNC_PODCAST_EDIT_POST: 'FUNC_PODCAST_EDIT_POST',
  FUNC_PODCAST_DELETE_POST: 'FUNC_PODCAST_DELETE_POST',
  FUNC_PODCAST_CONFIGURE: 'FUNC_PODCAST_CONFIGURE',
  FUNC_PODCAST_IMPORT_JSON: 'FUNC_PODCAST_IMPORT_JSON',
  // Feature-level: splash
  FUNC_SPLASH_MANAGE: 'FUNC_SPLASH_MANAGE',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Holding any of these unlocks the admin configuration surface
 * (GET /api/admin/config and the corresponding settings screens).
 * Deliberately permission-based, not role-based: roles are dynamic
 * (composite realm roles defined in Keycloak).
 */
export const ADMIN_CONFIG_PERMISSIONS: Permission[] = [
  PERMISSIONS.FUNC_TAB_SETTINGS_MANAGE_USERS,
  PERMISSIONS.FUNC_TAB_SETTINGS_CONFIGURE_AUTH,
  PERMISSIONS.FUNC_TAB_SETTINGS_SESSION_CONFIG,
  PERMISSIONS.FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS,
  PERMISSIONS.FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS,
  PERMISSIONS.FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT,
  PERMISSIONS.FUNC_TAB_SETTINGS_BRANDING,
];

export function canAccessAdminConfig(permissions: readonly string[]): boolean {
  return ADMIN_CONFIG_PERMISSIONS.some((p) => permissions.includes(p));
}

export const PERMISSION_LABELS: Record<Permission, string> = {
  FUNC_TAB_HOME: 'Home Tab',
  FUNC_TAB_FEED: 'Feed Tab',
  FUNC_TAB_SKATE_SQUARE: 'Skate Square Tab',
  FUNC_TAB_PODCAST: 'Podcast Tab',
  FUNC_TAB_SETTINGS: 'Settings Tab',
  FUNC_TAB_SETTINGS_MANAGE_USERS: 'Manage Users',
  FUNC_TAB_SETTINGS_MANAGE_USERS_INSERT: 'Create Users',
  FUNC_TAB_SETTINGS_MANAGE_USERS_UPDATE: 'Edit Users',
  FUNC_TAB_SETTINGS_MANAGE_USERS_DELETE: 'Delete Users',
  FUNC_TAB_SETTINGS_CONFIGURE_AUTH: 'Configure Authentication',
  FUNC_TAB_SETTINGS_SESSION_CONFIG: 'Session Configuration',
  FUNC_TAB_SETTINGS_LANGUAGE_SETTINGS: 'Language Settings',
  FUNC_TAB_SETTINGS_PROFILE_RESTRICTIONS: 'Profile Restrictions',
  FUNC_TAB_SETTINGS_NAVIGATION_MANAGEMENT: 'Navigation Management',
  FUNC_TAB_SETTINGS_BRANDING: 'Branding (Login Background)',
  FUNC_FEED_CREATE_POST: 'Create Posts',
  FUNC_FEED_EDIT_POST: 'Edit Posts',
  FUNC_FEED_DELETE_POST: 'Delete Posts',
  FUNC_FEED_CONFIGURE: 'Configure Feed',
  FUNC_FEED_IMPORT_JSON: 'Import Posts from JSON',
  FUNC_PODCAST_CREATE_POST: 'Create Podcast Posts',
  FUNC_PODCAST_EDIT_POST: 'Edit Podcast Posts',
  FUNC_PODCAST_DELETE_POST: 'Delete Podcast Posts',
  FUNC_PODCAST_CONFIGURE: 'Configure Podcast',
  FUNC_PODCAST_IMPORT_JSON: 'Import Podcast Posts from JSON',
  FUNC_SPLASH_MANAGE: 'Manage Splash Screens',
};

